name: Build Docs

defaults:
  run:
    shell: bash

on: [workflow_call, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04

    container: 
        image: koreader/koappimage:0.1.8
        # for now until docker crash fixed
        #image: koreader/koappimage:0.2.2
        options: --user ko
        
    env:
        EMULATE_READER: 1
        HOME: /home/ko
        # pretend to be cirleci so the scripts dont have to change
        WORKING_DIRECTORY: ${{ github.workspace }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
        # chown working directory to ko (docker user)
        # Allow ko user to access /__w/_temp/ directory to be able to save & restore cache
      - name: permissions
        run: sudo chown -R ko:ko /__w/doc/ && sudo chmod 777 /__w/_temp/

        # make sure we have git >= 2.18 so github checkout behaves
      - name: Update git ldoc
        run: sudo add-apt-repository ppa:git-core/ppa -y && sudo apt-get update && sudo apt-get install git lua-ldoc -y

      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup env
        run: echo "${HOME}/bin" | sudo tee -a $GITHUB_PATH

      - name:  docs
        run: .ci/docs.sh

