name: Build Docs

defaults:
  run:
    shell: bash

on: [workflow_call, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
        EMULATE_READER: 1
        HOME: /home/ko
        # pretend to be cirleci so the scripts dont have to change
        WORKING_DIRECTORY: ${{ github.workspace }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
        # make sure we have git >= 2.18 so github checkout behaves
      - name: Update ldoc
        run: sudo apt-get update && sudo apt-get install lua-ldoc -y

      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name:  docs
        run: .ci/docs.sh

